version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  web:
    build: .
    volumes:
      - static:/static
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static: