# Generated by Django 4.0.2 on 2022-02-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='BucketItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_items_bucket', to='product.bucket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_items_item', to='product.item')),
            ],
        ),
        migrations.AddField(
            model_name='bucket',
            name='items',
            field=models.ManyToManyField(related_name='item_bucket', through='product.BucketItems', to='product.Item'),
        ),
    ]
