# Generated by Django 4.0.2 on 2022-02-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_item', to='product.item'),
        ),
    ]
