# Generated by Django 4.0.2 on 2022-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_discount_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
