# Generated by Django 4.0.2 on 2022-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_discount_percent_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
