# Generated by Django 4.0.2 on 2022-02-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_promocodeactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode_name', models.CharField(max_length=8)),
                ('promocode_discount_percent', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
