# Generated by Django 4.0.2 on 2022-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromocodeActivity',
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='promocode_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='promocode',
            name='promocode_summ_discount',
            field=models.BooleanField(default=False),
        ),
    ]
