# Generated by Django 4.0.2 on 2022-02-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_cashback_alter_bucketitems_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_summ', models.DecimalField(decimal_places=15, max_digits=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
