# Generated by Django 4.0.2 on 2022-02-18 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCashbackAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount_use_cashback', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cashback',
            name='min_amount_use_cashback',
        ),
        migrations.AddField(
            model_name='cashback',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cashback',
            name='min_order_amout',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='_items_list',
            field=models.TextField(default='[]'),
        ),
    ]
