# Generated by Django 4.0.2 on 2022-02-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_add_default_value_for_min_amount_cachback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_items_list',
        ),
    ]
