# Generated by Django 4.0.2 on 2022-02-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_order__items_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account_id',
            new_name='account',
        ),
    ]
