# Generated by Django 4.0.2 on 2022-02-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_account_id_order_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_summ',
            new_name='order_sum',
        ),
    ]
