# Generated by Django 4.0.2 on 2022-02-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_order_summ_order_order_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashback',
            old_name='min_order_amout',
            new_name='min_order_amount',
        ),
    ]
