# Generated by Django 4.0.2 on 2022-03-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_order_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='delivery_date_time',
        ),
    ]
