# Generated by Django 3.2.12 on 2022-03-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_order_email_hours_before_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_before_delivery', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_hours_before_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='email_delivery_notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_emaildeliverynotification', to='product.emaildeliverynotification'),
        ),
    ]
