# Generated by Django 4.0.2 on 2022-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amount_accrued_cashback',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
