# Generated by Django 4.0.2 on 2022-03-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_customuser_amount_accrued_cashback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesEmailDeliveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_before_delivery', models.IntegerField()),
            ],
        ),
    ]
