# Generated by Django 4.0.2 on 2022-03-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_choicesemaildeliverynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicesemaildeliverynotification',
            name='title',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
