# Generated by Django 3.2.12 on 2022-03-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_choicesemaildeliverynotification_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoicesEmailDeliveryNotification',
        ),
    ]
