# Generated by Django 3.2.12 on 2022-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_delete_choicesemaildeliverynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_promotional_offers',
            field=models.BooleanField(default=False),
        ),
    ]
